CREATE DATABASE hotwaxdb;
USE hotwaxdb;

CREATE TABLE party (
    PARTY_ID VARCHAR(40) NOT NULL,
    PARTY_TYPE_ENUM_ID VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (PARTY_ID)
);

CREATE TABLE person (
    PARTY_ID VARCHAR(40) NOT NULL,
    SALUTATION VARCHAR(255) DEFAULT NULL,
    FIRST_NAME VARCHAR(255) DEFAULT NULL,
    MIDDLE_NAME VARCHAR(255) DEFAULT NULL,
    LAST_NAME VARCHAR(255) DEFAULT NULL,
    GENDER CHAR(1) DEFAULT NULL,
    BIRTH_DATE DATE DEFAULT NULL,
    MARITAL_STATUS_ENUM_ID VARCHAR(40) DEFAULT NULL,
    EMPLOYMENT_STATUS_ENUM_ID VARCHAR(40) DEFAULT NULL,
    OCCUPATION VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (PARTY_ID),
    FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID)
);

CREATE TABLE product (
    PRODUCT_ID VARCHAR(40) NOT NULL,
    OWNER_PARTY_ID VARCHAR(40) DEFAULT NULL,
    PRODUCT_NAME VARCHAR(255) DEFAULT NULL,
    DESCRIPTION VARCHAR(4095) DEFAULT NULL,
    CHARGE_SHIPPING CHAR(1) DEFAULT NULL,
    RETURNABLE CHAR(1) DEFAULT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (OWNER_PARTY_ID) REFERENCES party(PARTY_ID)
);

CREATE TABLE order_header (
    ORDER_ID VARCHAR(40) NOT NULL,
    ORDER_NAME VARCHAR(255) DEFAULT NULL,
    PLACED_DATE DATETIME DEFAULT NULL,
    APPROVED_DATE DATETIME DEFAULT NULL,
    STATUS_ID VARCHAR(40) DEFAULT NULL,
    CURRENCY_UOM_ID VARCHAR(40) DEFAULT NULL,
    PRODUCT_STORE_ID VARCHAR(40) DEFAULT NULL,
    SALES_CHANNEL_ENUM_ID VARCHAR(40) DEFAULT NULL,
    GRAND_TOTAL DECIMAL(24,4) DEFAULT NULL,
    COMPLETED_DATE DATETIME DEFAULT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE order_part (
    ORDER_ID VARCHAR(40) NOT NULL,
    ORDER_PART_SEQ_ID VARCHAR(40) NOT NULL,
    PART_NAME VARCHAR(255) DEFAULT NULL,
    STATUS_ID VARCHAR(40) DEFAULT NULL,
    VENDOR_PARTY_ID VARCHAR(40) DEFAULT NULL,
    CUSTOMER_PARTY_ID VARCHAR(40) DEFAULT NULL,
    PART_TOTAL DECIMAL(24,4) DEFAULT NULL,
    FACILITY_ID VARCHAR(40) DEFAULT NULL,
    SHIPMENT_METHOD_ENUM_ID VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (ORDER_ID, ORDER_PART_SEQ_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES order_header(ORDER_ID),
    FOREIGN KEY (CUSTOMER_PARTY_ID) REFERENCES party(PARTY_ID)
);


INSERT INTO party (PARTY_ID, PARTY_TYPE_ENUM_ID)
VALUES ('ORG_ZIZI_RETAIL', 'PtyOrganization');

INSERT INTO party (PARTY_ID, PARTY_TYPE_ENUM_ID)
VALUES ('CustJqp', 'PtyPerson');

INSERT INTO party (PARTY_ID, PARTY_TYPE_ENUM_ID)
VALUES ('CustDemo2', 'PtyPerson');


INSERT INTO product (PRODUCT_ID, OWNER_PARTY_ID, PRODUCT_NAME, DESCRIPTION, CHARGE_SHIPPING, RETURNABLE)
VALUES ('DEMO_UNIT', 'ORG_ZIZI_RETAIL', 'Demo Product One Unit', '', 'Y', 'Y');

INSERT INTO product (PRODUCT_ID, OWNER_PARTY_ID, PRODUCT_NAME, DESCRIPTION, CHARGE_SHIPPING, RETURNABLE)
VALUES ('DEMO_1_1', 'ORG_ZIZI_RETAIL', 'Demo Product One One', '', 'Y', 'Y');

INSERT INTO product (PRODUCT_ID, OWNER_PARTY_ID, PRODUCT_NAME, DESCRIPTION, CHARGE_SHIPPING, RETURNABLE)
VALUES ('DEMO_1_2', 'ORG_ZIZI_RETAIL', 'Demo Product One Two', '', 'Y', 'Y');

